library:
  source-dirs: src
tests:
  kwoka-test:
    source-dirs: test
    main: Spec.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - kwoka
copyright: 2019 Author name here
maintainer: example@example.com
dependencies:
- mtl
- containers
- parser-combinators
- megaparsec
- base >= 4.7 && < 5
name: kwoka
version: 0.1.0.0
extra-source-files:
- README.md
- ChangeLog.md
author: Author name here
github: githubuser/kwoka
license: BSD3
executables:
  kwoka-exe:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Werror
    dependencies:
    - kwoka
description: Please see the README on GitHub at <https://github.com/githubuser/kwoka#readme>
